/*
 * @Author: shen
 * @Date: 2025-06-30 15:24:55
 * @LastEditors: shen
 * @LastEditTime: 2025-08-23 13:23:04
 * @Description:
 */
import { parseEnv } from '../utils'

const {
  VITE_APP_NAME,
  VITE_USE_MOCK,
  VITE_PUBLIC_PATH,
  VITE_APP_TITLE,
  VITE_ENCRYPE,
  VITE_APP_THEME_COLOR,
  VITE_APP_SUCCESS_COLOR,
  VITE_APP_ERROR_COLOR,
  VITE_APP_WARNING_COLOR,
  VITE_APP_INFO_COLOR,
  VITE_APP_LANGUAGE,
  VITE_API_URL_PREFIX,
  VITE_WS_URL_PREFIX,
  VITE_UPLOAD_URL_PREFIX,
  VITE_APP_NAMESPACE,
  VITE_APP_ANTD_PREFIX_CLS,
  VITE_APP_DARK_MODE,
  VITE_REQUEST_MOCK,
  VITE_APP_VERSION,
  VITE_APP_STORAGE_SECURE_KEY,
  VITE_APP_STORAGE_ENCRYPE,
  VITE_ROUTER_HISTORY,
  VITE_LOGGER_LEVEL,
  VITE_MAIN_APP,
} = parseEnv(import.meta.env)

export {
  VITE_APP_NAME,
  VITE_USE_MOCK,
  VITE_PUBLIC_PATH,
  VITE_APP_TITLE,
  VITE_ENCRYPE,
  VITE_APP_THEME_COLOR,
  VITE_APP_SUCCESS_COLOR,
  VITE_APP_ERROR_COLOR,
  VITE_APP_WARNING_COLOR,
  VITE_APP_INFO_COLOR,
  VITE_APP_LANGUAGE,
  VITE_API_URL_PREFIX,
  VITE_WS_URL_PREFIX,
  VITE_UPLOAD_URL_PREFIX,
  VITE_APP_NAMESPACE,
  VITE_APP_ANTD_PREFIX_CLS,
  VITE_APP_DARK_MODE,
  VITE_REQUEST_MOCK,
  VITE_APP_VERSION,
  VITE_APP_STORAGE_SECURE_KEY,
  VITE_APP_STORAGE_ENCRYPE,
  VITE_ROUTER_HISTORY,
  VITE_LOGGER_LEVEL,
  VITE_MAIN_APP,
}
