name: Publish Site Deploy (Manual)

on: workflow_dispatch

jobs:
  deploy-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "pnpm_cache_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build website
        run: pnpm build
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          git-config-name: xh-shen
          git-config-email: 9509394@qq.com
          commit-message: website deploy

      - name: Deploy to vercel
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          token: ${{ secrets.PRO_BOT_TOKEN }}
          branch: main
          folder: dist
          repository-name: pro-design-vue/admin-staging
          git-config-name: xh-shen
          git-config-email: 9509394@qq.com
